name: CI - Push to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  issues: write
  repository-projects: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}
  
      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main
  
      - name: Format code
        run: pnpm run lint:fix
  
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: '[ci] lint'
          branch: ${{ github.head_ref }}
          commit_user_name: studiocms-no-reply
          commit_user_email: no-reply@studiocms.dev
          commit_author: StudioCMS <no-reply@studiocms.dev>

  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/release.yml@a08b74527cb0ddb4a392bf44d3e28b36bf282a8a # main
    with:
      build-cmd: "pnpm ci:build"
      RoleMentionId: '1309310416362537020'